export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_ERROR = "FETCH_WEATHER_ERROR";
export const FETCH_LAT_LNG = "FETCH_LAT_LNG";
export const FETCH_LAT_LNG_SUCCESS = "FETCH_LAT_LNG_SUCCESS";